spring.datasource.url=jdbc:postgresql://localhost:5432/vola
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# === AWS (dummy values for local dev) ===
aws.eventBridge.bus=dummy-bus
aws.s3.bucket=dummy-bucket
aws.ses.source=noreply@example.com

# === Orange Money ===
orange.api.url=http://localhost:9999
